### ISSUE TITLE
Page Organization

### ISSUE THREAD

**Issue by ellioterwin** [zentrification/ellioterwin.com#4]
1) Kill Branding and Extras pages.
2) Make Projects the home page
3) remove drop down from 'Projects' on menu bar.

**Comment by zentrification** [comment]
Looks like you removed branding & extras pages from nav.

Just made projects the homepage, and changed the projects dropdown to only appear in development mode.
Deployed here
http://ellioterwin.com.s3-website-us-east-1.amazonaws.com/
