### ISSUE TITLE
Grid Alignment

### ISSUE THREAD

**Issue by ellioterwin** [zentrification/ellioterwin.com#5]
1) Id like grids to align cleanly and crop image instead of doing this
![image](https://user-images.githubusercontent.com/6400398/87480134-afca7b80-c5fa-11ea-9ccd-27ee0b51b3c4.png)

**Comment by zentrification** [comment]
Best approach here is probably to crop all the images to the same aspect ratio.

Image on the left is 728x1116 px
Image on the right is 792x1116 px
